apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuponing-deployment
  labels:
    app: cuponing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cuponing
  template:
    metadata:
      labels:
        app: cuponing
    spec:
      containers:
      - name: cuponing
        image: hugoangeles0810/cloud-microservices-poc-cuponing:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cuponing-service
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30002
  selector:
    app: cuponing